name: Shell
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
